Update build_a52q.yml

diff --git a/.github/workflows/build_a52q.yml b/.github/workflows/build_a52q.yml
--- a/.github/workflows/build_a52q.yml
+++ b/.github/workflows/build_a52q.yml
@@ -36,8 +36,6 @@ jobs:
               KERNELSU_NAME
               SUSFS_ENABLE
               SUSFS_FIXED
-              PATCHES_SOURCE
-              PATCHES_BRANCH
               AK3_SOURCE
               AK3_BRANCH
               BOOT_SOURCE
@@ -92,23 +90,19 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/device_kernel
           echo "CONFIG_KSU=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
-            echo "CONFIG_KSU_SUSFS=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-            echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-            echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-            echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-            echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-            echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-            echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-            echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-            echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-            echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-          fi
+          echo "CONFIG_KSU_SUSFS=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
 
-      - name: Set Pack Method and KernelSU and SUSFS
+      - name: Set Pack Method and KernelSU
         run: |
-          SUSFS_SOURCE=https://gitlab.com/simonpunk/susfs4ksu.git
-          SUSFS_BRANCH=kernel-${{ env.KERNEL_VERSION }}
           PACK_METHOD=Anykernel3
           KERNELSU_METHOD=shell
           
@@ -120,16 +114,14 @@ jobs:
           echo "KERNELSU_METHOD=$KERNELSU_METHOD" >> $GITHUB_ENV
           KSU_VERSION=$(cd ${{ env.KERNELSU_NAME }} && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
           echo "UPLOADNAME=-${{ env.KERNELSU_NAME }}_$KSU_VERSION" >> $GITHUB_ENV
-          
-          if [[ "${{ env.SUSFS_ENABLE }}" == true ]]; then
-            git clone $SUSFS_SOURCE -b $SUSFS_BRANCH susfs4ksu --depth=1
-            cp susfs4ksu/kernel_patches/fs/* fs/
-            cp susfs4ksu/kernel_patches/include/linux/* include/linux/
-          fi
 
       - name: Patch Kernel for no-kprobe
         run: |
           cd $GITHUB_WORKSPACE
+          if [ ! -d "device_kernel" ]; then
+            echo "ERROR: device_kernel directory does not exist!"
+            exit 1
+          fi
           if [[ -f "/tmp/Patches/normal_patches.sh" ]]; then
             cp /tmp/Patches/normal_patches.sh $GITHUB_WORKSPACE/device_kernel/
             cd $GITHUB_WORKSPACE/device_kernel
@@ -148,23 +140,13 @@ jobs:
           touch $GITHUB_WORKSPACE/system/core/liblog/include/log/perflog.h
           echo "Created dummy perflog.h"
 
-      - name: Patch Kernel of SUSFS
-        if: env.SUSFS_ENABLE == 'true'
+      - name: Disable Module Signing
         run: |
-          cd $GITHUB_WORKSPACE/device_kernel/
-          cp susfs4ksu/kernel_patches/50_add_susfs_in_kernel-4.14.patch ./
-          patch -p1 < 50_add_susfs_in_kernel-4.14.patch || true
-
-      - name: Fixed Kernel Patch
-        if: env.SUSFS_ENABLE == 'true' && env.SUSFS_FIXED == 'true'
-        run: |
-          cd $GITHUB_WORKSPACE/device_kernel/
-          cp NonGKI_Kernel_Patches/kona_oos/namespace_fixed.patch ./ 2>/dev/null || true
-          cp NonGKI_Kernel_Patches/kona_oos/task_mmu_fixed.patch ./ 2>/dev/null || true
-          cp NonGKI_Kernel_Patches/kona_oos/ksu_backport.patch ./ 2>/dev/null || true
-          patch -p1 < namespace_fixed.patch || true
-          patch -p1 < task_mmu_fixed.patch || true
-          patch -p1 < ksu_backport.patch || true
+          cd $GITHUB_WORKSPACE/device_kernel
+          sed -i 's/CONFIG_MODULE_SIG=y/# CONFIG_MODULE_SIG is not set/g' arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          sed -i 's/CONFIG_MODULE_SIG_ALL=y/# CONFIG_MODULE_SIG_ALL is not set/g' arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          sed -i 's/CONFIG_MODULE_SIG_FORCE=y/# CONFIG_MODULE_SIG_FORCE is not set/g' arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+          echo "Disabled module signing."
 
       - name: Build Kernel
         run: |
